services:
  secure_coding:
    image: secure_coding_lab
    environment:
      - VAULT_ADDR=http://vault:8200
    volumes:
      - ./local_data:/local_data
    cap_add:
      - CAP_IPC_LOCK
    links:
      - postgres
      - vault
    command: ["/usr/bin/sleep", "infinite"]
    build:
      dockerfile: ./secure_coding.Dockerfile
      context: .
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=not_so_secure_default_password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  vault:
    image: vault
    restart: always
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
      # - VAULT_DEV_ROOT_TOKEN_ID=hvs.insecure_token
    links:
      - postgres
    cap_add:
      - CAP_IPC_LOCK
    ports:
      - "8200:8200"

volumes:
  db:
    driver: local
